apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volumeclaim
  labels:
    app: wordpress
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
